name: 'Export Scribus PDF'
description: 'Export a PDF file from a Scribus/.sla file'
inputs:
  sla-file:  # id of input
    description: 'Input .sla file'
    required: true
    #default: 'file.sla'
outputs:
  pdf-file: # id of output
    description: 'Output PDF file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sla-file }}
